version: 2
jobs: 
    working_directory: /tmp/workspace
    steps:
      - run: echo "====================构建开始=============================="
      - run: echo "====================构建完毕=============================="
  deploy:
    java:
      version: oraclejdk8     
    working_directory: /tmp/workspace
    steps:
      - run: echo "====================部署开始=============================="
      - attach_workspace:
          at: /tmp/workspace
      - run: pwd && ls -al
      - run:
          name: Deploy 
          command: |          |
  curl -LO https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/master/tools/build_chain.sh && chmod u+x build_chain.sh
  bash <(curl -s https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/master/tools/ci/download_bin.sh) -b master
  echo "127.0.0.1:4 agency1 1,2,3" > ipconf
  ./build_chain.sh -e bin/fisco-bcos -f ipconf -p 30300,20200,8545
  ./nodes/127.0.0.1/start_all.sh
  cp nodes/127.0.0.1/sdk/* src/main/resources/
  ./gradlew verGJF
  ./gradlew build
      - run: echo "====================部署完毕=============================="
