encrypt-type: 0  # 0:standard, 1:guomi
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - 127.0.0.1:20200  # node listen_ip:channel_listen_port
                    - 127.0.0.1:20201
 
channel-service:
  group-id: 1 # The specified group to which the SDK connects
  org-id: fisco # agency name

user-key:
  user-key: 9099ffe712c486fd0f255844de197b8c763f38ca542ba3038974dc04b3ae48ec

#9099ffe712c486fd0f255844de197b8c763f38ca542ba3038974dc04b3ae48ec

#603cd8f3bdf765f684e61250ec20ef3117618a398b342772fb6a8a1fabdb139f

# user key

